### ISSUE TITLE
文章中可能有小笔误，引用了错误的寄存器名称

### ISSUE THREAD

**Issue by Howlaind** [cch123/asmshare#1]
在 layout.md 的「基本概念·基础指令」一节内，对汇编命令 `pop rax` 的解释为：

> 将 `rsp` 指向的内存位置的 8 个字节移动到 `rax`，并将 **`rax`** 从栈顶下移 8 个字节

其中后一句「并将 **`rax`** 从栈顶下移 8 个字节」中的 `rax` 是否为 `rsp` 的笔误呢？

**Comment by cch123** [comment]
感谢提出，是写错了，我改一下

**Comment by cch123** [comment]
已修复，https://github.com/cch123/asmshare/commit/64f1f995d670c5508a2054d2a2e58d3c1feba5c7
